name: Deploy Python Lambda

on:
  push:
    branches:
      - prod
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
permissions:
  id-token: write
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: configure aws credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::199195409647:role/media_micro_role
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: us-west-1
      - name: Deploy Modified Files
        run: |
          cd src
          mkdir lambda
          cp -r ./media_microservice ./lambda/${{ secrets.MICRO_SV_KEY }}
          cd lambda
          zip -r ../media_microservice_lambda.zip .
          cd ..

          # Upload the updated zip to S3
          aws s3 cp media_microservice_lambda.zip s3://${{ secrets.AWS_BUCKET }}/${{ secrets.MICRO_SV_KEY }}/

          # Upload requirements for Lambda Layer
          aws s3 cp ../requirements.txt s3://${{ secrets.AWS_BUCKET }}/${{ secrets.MICRO_SV_KEY }}/

          rm -r lambda
          rm media_microservice_lambda.zip
