name: Labeler

on:
  push:
    branches:
      - prod
jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Check CWD
        run: |
          echo "$PWD"

      - name: Run Labeler
        uses: crazy-max/ghaction-github-labeler@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: ./.github/workflows/labels.yml
          skip-delete: true
